Prepare 1.x draft version; restore discussion of W3C VC credential source
creator-assertions/identity-assertion pull request #60
Opened 2024-02-28 18:49 UTC by scouten-adobe

2024-03-04 16:45 UTC, OR13 requested changes
I would like to see this target W3C VC Data Model v2

I don't think it is good to try to target both v1 and v2

2024-03-04 16:46 UTC, OR13 commented on docs/modules/ROOT/pages/index.adoc
> +* https://www.w3.org/TR/vc-data-model/[W3C verifiable credentials data model, version 1.1]
```suggestion
* https://www.w3.org/TR/vc-data-model-2.0/[Verifiable Credentials Data Model v2.0]
```

2024-03-04 16:47 UTC, OR13 commented on docs/modules/ROOT/pages/index.adoc
> +    "https://w3id.org/security/suites/jws-2020/v1"
```suggestion
    "https://www.w3.org/ns/security/jwk/v1"
```

2024-03-04 16:49 UTC, OR13 commented on docs/modules/ROOT/pages/index.adoc
> +
```suggestion

TODO: Add a table of supported media types for *secured* verifiable credentials. For example:

- application/vc+ld+json+cose
- application/vc+ld+json+jwt
- application/vc+ld+json+sd-jwt

TODO: Define which are mandatory to implement and which are optional.

```

2024-03-19 18:12 UTC, scouten-adobe commented
@or13 please re-review when you have a moment. I've removed all references to VC 1.1

2024-04-01 20:52 UTC, closed without merging

2024-04-01 20:52 UTC, scouten-adobe commented
Closed in favor of #85 per discussion in 01 April 2024 meeting.