Clarify that `pad1` and `pad2` must only be filled with zero-value (0x00) bytes
creator-assertions/identity-assertion pull request #79
Opened 2024-03-18 23:27 UTC by scouten-adobe

Responding to PR feedback from @lrosenthol in https://github.com/creator-assertions/identity-assertion/pull/75#discussion_r1527635129.

2024-03-19 19:25 UTC, lrosenthol requested changes

2024-03-19 19:25 UTC, lrosenthol commented on docs/modules/ROOT/pages/index.adoc
> +* `pad1` and `pad2` are zero-value (`0x00`) byte strings used to fill space
```suggestion
* `pad1` and `pad2` are zero-filled (binary `\0` values) byte strings used to fill space
```

2024-03-19 19:25 UTC, lrosenthol commented on docs/modules/ROOT/pages/index.adoc
> +  "pad1": bstr, ; zero-value (`0x00`) byte string used for filling up space
```suggestion
  "pad1": bstr, ; zero-filled (binary `\0` values) byte string used for filling up space
```

2024-03-19 19:25 UTC, lrosenthol commented on docs/modules/ROOT/pages/index.adoc
> +  ? "pad2": bstr, ; optional zero-value (`0x00`) byte string used for filling up space
```suggestion
  ? "pad2": bstr, ; optional zero-filled (binary `\0` values) byte string used for filling up space
```

2024-03-19 19:28 UTC, lrosenthol commented on docs/modules/ROOT/pages/index.adoc
> +* `pad1` and `pad2` are zero-filled (binary `\0` values) byte strings used to fill space
```suggestion
* `pad1` and `pad2` are zero-filled (binary `0x00` values) byte strings used to fill space
```

2024-03-19 19:28 UTC, lrosenthol approved these changes

2024-03-25 16:21 UTC, scouten-adobe commented on docs/modules/ROOT/pages/index.adoc
> +* `pad1` and `pad2` are zero-filled (binary `0x00` values) byte strings used to fill space
Suggested reword: ... are byte strings filled with binary `0x00` values ...

2024-03-25 16:22 UTC, scouten-adobe commented
Per 25 March 2024, meeting :+1: to merge with wording changes as noted.

2024-03-25 21:01 UTC, merged